replicaCount: 1

image:
  repository: nihal2000/java-student-app
  tag: latest
  pullPolicy: IfNotPresent

# 🚀 यहाँ हमने असली क्रेडेंशियल्स को डिक्लेरेटिवली इंजेक्ट कर दिया है
env:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "postgres-service"       # तुम्हारी कुबेरनेटीज़ PostgreSQL सर्विस का नाम
  DB_PORT: "5432"                    # क्लस्टर के अंदर का इंटरनल पोर्ट हमेशा 5432 होता है भाई
  DB_NAME: "Task1"
  DB_USER: "postgres"
  DB_PASSWORD: "admin"               # जो तुम्हारी प्रॉपर्टीज फाइल में 'admin' मिला है

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: api.studentmgmt.local