apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-student-app
  labels:
    app: java-student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-student-app
  template:
    metadata:
      labels:
        app: java-student-app
    spec:
      containers:
      - name: java-app-container
        image: "nihal2000/java-student-app:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/Task1"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES
          value: "true"
        - name: SPRING_KAFKA_LISTENER_AUTO_STARTUP
          value: "false"
        - name: APP_KAFKA_STUDENT_LOGIN_TOPIC
          value: "student-login-topic"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "localhost:9092"
        - name: SPRING_MAIL_HOST
          value: "localhost"
        - name: SPRING_MAIL_PORT
          value: "25"
        - name: SPRING_MAIL_USERNAME
          value: "dummy@gmail.com"
        - name: SPRING_MAIL_PASSWORD
          value: "dummypassword"
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: "student-app-group"
        # 👇 ये दोनों लाइनें स्प्रिंग सिक्योरिटी के OAuth2 एरर को शांत कर देंगी
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
          value: "dummy-client-id"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
          value: "dummy-client-secret"