apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-student-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: api.studentmgmt.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: java-student-service
            port:
              number: 80