replicaCount: 1

image:
  repository: nihal2000/java-student-app
  tag: latest
  pullPolicy: IfNotPresent

# 🚀 बिना प्रॉपर्टीज फ़ाइल के, ये वेरिएबल्स सीधे स्प्रिंग बूट को लाइव कर देंगे
env:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://172.17.0.1:5433/Task1"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "admin"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES: "true"
  SPRING_KAFKA_LISTENER_AUTO_STARTUP: "false" # काफ्का बंद है, इसलिए इसे फॉल्स रखना ज़रूरी है भाई

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: api.studentmgmt.local